/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,css}",
    "./**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f2",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dfc71f",
        "surface-variant": "#e5e2e1",
        "tertiary": "#6b5e00",
        "on-primary-fixed": "#002112",
        "outline-variant": "#c1c8c1",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#a4d1b4",
        "surface-container": "#f0edec",
        "primary": "#3e6750",
        "on-primary-container": "#3e6750",
        "secondary-container": "#e7d6fe",
        "on-background": "#1c1b1b",
        "tertiary-fixed": "#fde33f",
        "primary-fixed-dim": "#a4d1b4",
        "background": "#fcf9f8",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "surface-tint": "#3e6750",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#c0edd0",
        "on-primary-fixed-variant": "#264f39",
        "on-surface": "#1c1b1b",
        "on-secondary-container": "#685b7d",
        "tertiary-container": "#f4da36",
        "secondary-fixed-dim": "#d0c0e7",
        "on-tertiary-fixed": "#211c00",
        "on-secondary-fixed-variant": "#4d4161",
        "secondary-fixed": "#ecdcff",
        "on-tertiary-fixed-variant": "#514700",
        "on-secondary-fixed": "#211633",
        "surface-container-high": "#ebe7e7",
        "primary-container": "#b7e4c7",
        "on-surface-variant": "#414943",
        "on-tertiary-container": "#6c5f00",
        "on-secondary": "#ffffff",
        "surface": "#fcf9f8",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "outline": "#717973",
        "on-primary": "#ffffff",
        "secondary": "#65587a",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1440px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["Bodoni Moda", "serif"],
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "headline-xl": ["Bodoni Moda", "serif"],
        "body-xl": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"]
      }
    }
  },
  plugins: [],
};